export const Videos = [
  {
    id: 1,
    title: "O Casamento é uma aliança",
    description: "Entenda como o casamento representa uma aliança profunda e significativa entre duas pessoas.",
    url: "https://player.vimeo.com/video/395600047",
    thumbnail: "https://i.ytimg.com/vi/yWOgUmg37v4/maxresdefault.jpg",
    releasedate: "2025-05-28",
  },
  {
    id: 2,
    title: "A aliança do limiar",
    description: "Descubra o significado da aliança do limiar e sua importância nas relações.",
    url: "https://player.vimeo.com/video/395600127",
    thumbnail: "https://i.ytimg.com/vi/yWOgUmg37v4/maxresdefault.jpg",
    releasedate: "2025-05-29",
  },
  {
    id: 3,
    title: "Como entender e resolver os conflitos",
    description: "Aprenda estratégias para compreender e solucionar conflitos de forma saudável.",
    url: "https://player.vimeo.com/video/395600179",
    thumbnail: "https://i.ytimg.com/vi/yWOgUmg37v4/maxresdefault.jpg",
    releasedate: "2025-05-30",
  },
  {
    id: 4,
    title: "A chave para a intimidade",
    description: "Veja como a intimidade pode ser fortalecida através de atitudes e escolhas conscientes.",
    url: "https://player.vimeo.com/video/395600218",
    thumbnail: "https://i.ytimg.com/vi/yWOgUmg37v4/maxresdefault.jpg",
    releasedate: "2025-05-31",
  },
  {
    id: 5,
    title: "Perdão",
    description: "Saiba como o perdão é essencial para restaurar relacionamentos e promover a paz.",
    url: "https://player.vimeo.com/video/395600263",
    thumbnail: "https://i.ytimg.com/vi/yWOgUmg37v4/maxresdefault.jpg",
    releasedate: "2025-06-01",
  },
  {
    id: 6,
    title: "Praticando o perdão",
    description: "Descubra maneiras práticas de exercer o perdão no dia a dia.",
    url: "https://player.vimeo.com/video/395600347",
    thumbnail: "https://i.ytimg.com/vi/yWOgUmg37v4/maxresdefault.jpg",
    releasedate: "2025-06-02",
  },
  {
    id: 7,
    title: "Utilizando o conflito para identificar suas causas",
    description: "Entenda como os conflitos podem revelar causas profundas e promover crescimento pessoal.",
    url: "https://player.vimeo.com/video/395600388",
    thumbnail: "https://i.ytimg.com/vi/yWOgUmg37v4/maxresdefault.jpg",
    releasedate: "2025-06-03",
  },
  {
    id: 8,
    title: "Restaurando o valor da aliança na sociedade",
    description: "Veja como resgatar o valor das alianças e compromissos na sociedade atual.",
    url: "https://player.vimeo.com/video/407182583",
    thumbnail: "https://i.ytimg.com/vi/yWOgUmg37v4/maxresdefault.jpg",
    releasedate: "2025-06-04",
  },
  {
    id: 9,
    title: "Restaurando o valor da aliança no casamento",
    description: "Aprenda a importância de restaurar e fortalecer a aliança no casamento.",
    url: "https://player.vimeo.com/video/407182710",
    thumbnail: "https://i.ytimg.com/vi/yWOgUmg37v4/maxresdefault.jpg",
    releasedate: "2025-06-05",
  },
  {
    id: 10,
    title: "Os componentes da aliança de sangue",
    description: "Conheça os elementos fundamentais que compõem a aliança de sangue.",
    url: "https://player.vimeo.com/video/407182838",
    thumbnail: "https://i.ytimg.com/vi/yWOgUmg37v4/maxresdefault.jpg",
    releasedate: "2025-06-06",
  },
];
